apiVersion: v1
kind: Namespace
metadata:
  name: sunny-boy-bigquery-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sunny-boy-bigquery-exporter
  namespace: sunny-boy-bigquery-exporter
  labels:
    app: sunny-boy-bigquery-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunny-boy-bigquery-exporter
  namespace: sunny-boy-bigquery-exporter
  labels:
    app: sunny-boy-bigquery-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sunny-boy-bigquery-exporter
  template:
    metadata:
      labels:
        app: sunny-boy-bigquery-exporter
    spec:
      restartPolicy: Always
      serviceAccount: sunny-boy-bigquery-exporter
      containers:
      - name: sunny-boy-bigquery-exporter
        image: jsalverda/sunny-boy-bigquery-exporter:${CONTAINER_TAG}
        env:
        - name: BQ_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: bq-project-id
              name: sunny-boy-bigquery-exporter-configs
        - name: BQ_DATASET
          valueFrom:
            configMapKeyRef:
              key: bq-dataset
              name: sunny-boy-bigquery-exporter-configs
        - name: BQ_TABLE
          valueFrom:
            configMapKeyRef:
              key: bq-table
              name: sunny-boy-bigquery-exporter-configs
        - name: SUNNY_BOY_HOST_IP
          valueFrom:
            configMapKeyRef:
              key: sunny-boy-host-ip
              name: sunny-boy-bigquery-exporter-configs
        - name: SUNNY_BOY_HOST_PORT
          valueFrom:
            configMapKeyRef:
              key: sunny-boy-host-port
              name: sunny-boy-bigquery-exporter-configs
        - name: SUNNY_BOY_USER
          valueFrom:
            configMapKeyRef:
              key: sunny-boy-user
              name: sunny-boy-bigquery-exporter-configs
        - name: SUNNY_BOY_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: sunny-boy-password
              name: sunny-boy-bigquery-exporter-configs
        - name: UDP_LOCAL_PORT
          valueFrom:
            configMapKeyRef:
              key: udp-local-port
              name: sunny-boy-bigquery-exporter-configs
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/keyfile.json
        ports:
        - name: udp
          containerPort: 8855
          protocol: UDP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: secrets
          mountPath: /secrets
      hostNetwork: true
      terminationGracePeriodSeconds: 300
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: sunny-boy-bigquery-exporter-credentials